### ISSUE TITLE
WoA Installer does not run

### ISSUE THREAD

**Issue by janisozaur** [WOA-Project/WoA-Installer-Rpi#37]
Trying to run `mono Installer.Raspberry.Application.exe` (the one from https://github.com/WOA-Project/WoA-Installer/releases/tag/1.5) results in following message:

> `The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

and exits immediately afterwards.

**Comment by SuperJMN** [comment]
Mono? This only run on Windows 10 😅

**Comment by janisozaur** [comment]
Why?

**Comment by moisesmcardona** [comment]
Mono does not support WPF

**Comment by SuperJMN** [comment]
Not only that, this tool uses DISM, BCDEDIT and BCDBOOT tools internally. I seriously doubt it could work in Linux some day.
