### ISSUE TITLE
install on USB flash drive ?

### ISSUE THREAD

**Issue by ErfanDL** [WOA-Project/WoA-Installer-Rpi#40]
Hi thanks for this nice project. can I install the OS in the USB flash drive ?
thanks

**Comment by 110101011** [comment]
That doesn't seem to work, I've tried it on a usb flash drive and resulted in a kernel panic at first boot.

**Comment by SuperJMN** [comment]
It's not possible. Please take a look at the [FAQ](https://pi64.win/)
