### ISSUE TITLE
I can't visit The core package link on onedrive, maybe it's the onedirve' s bug

### ISSUE THREAD

**Issue by HunterQu** [WOA-Project/WoA-Installer-Rpi#41]
Just like the tittle, could you please send me the package, qhxhunter@gmail.com thanks!!

**Comment by CornyjK** [comment]
Use private mode of browser.

**Comment by HunterQu** [comment]
Well, it doesn't work.??

**Comment by CornyjK** [comment]
Clear browser cache, use another browser, another computer.
