### ISSUE TITLE
Booting ends up in UEFI Shell

### ISSUE THREAD

**Issue by ntnlabs** [WOA-Project/WoA-Installer-Rpi#42]
Prerequisites: Windows 1809 sk version, WoA 1.2, Core 1.4.0.

Issue: after boot system stays in UEFI Shell.

Quick Fix: reboot (with command), press ESC to go to setup, then there is a menu (my system is still booting, after that I will post exact menu location) You can choose to boot UEFi or Windows. If You choose Windows it will boot up successfully.

Proper fix: UEFI setup to boot to the right partition (or how is it called in UEFI)...

**Comment by SuperJMN** [comment]
That's expected with the latest UEFI :) 
Please, check this. https://discourse.pi64.win/t/frequently-asked-questions-faq/49/5
