### ISSUE TITLE
What about A2 SD cards?

### ISSUE THREAD

**Issue by LoekHabets** [WOA-Project/WoA-Installer-Rpi#44]
I'm considering picking up a new SD card for this because the best I have now is a 16GB Class 10 SD card. Windows 10 works, but according to task manager, the SD card is maxed almost 100% of the time. It can barely keep up and it's very noticeble.

So you recommend using an A1 card, but why? A2 cards have better specs and they're barely more expensive. Is there an issue with hardware support or does the performance advantage of A2 cards not really materialize on the Pi?

**Comment by CornyjK** [comment]
You could try, but I don't know if we have drivers for it.

**Comment by CornyjK** [comment]
Not a topic for this issue tracker anyways.
