### ISSUE TITLE
Error code 112

### ISSUE THREAD

**Issue by princessAmy** [WOA-Project/WoA-Installer-Rpi#45]
I downloaded the required files and started the installation, but it seems to work fine until I get up to 64 %, and then it says, Error code 112, there has been a problem during your deployment: DISM exited with code 112

**Comment by patel8786** [comment]
I get the same error.

Is it looking for DISM in the wrong place? 

Windows 10 documentation says:
> DISM comes with Windows 10, in the `c:\windows\system32` folder, but you can run DISM in the command prompt from any location. You have to be running from a Command Prompt as administrator to use use DISM.

I can see DISM.exe in that folder but it's looking for it in `C:\WINDOWS\SysNative\dism.exe`
The logging seems to say that DISM was started and returned the error code but I'm doubting that.

I've copied dism.exe and the dism folder from `system32 `to `C:\WINDOWS\SysNative\` and going to try again.

> 2019-02-17 21:55:35.658 +02:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "3204780842", Images: [ImageMetadata { DirectoryCount: "19016", FileCount: "85770", TotalBytes: "13896743737", HardLinkBytes: "6092415839", CreationTime: Time { HighPart: "0x01D4C09E", LowPart: "0xE35BD26F" }, LastModificationTime: Time { HighPart: "0x01D4C09F", LowPart: "0xA17D02E1" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Core", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.18836.1000;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-GB", Default: "en-GB" }, Version: Version { Major: "10", Minor: "0", Build: "18836", SpBuild: "1000", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Home", Description: "Windows 10 Home", Flags: null, DiplayName: "Windows 10 Home", DisplayDescription: "Windows 10 Home", Index: "1" }] }
2019-02-17 21:55:35.659 +02:00 [Verbose] We are about to run DISM: "C:\WINDOWS\SysNative\dism.exe" "/Apply-Image /ImageFile:\"C:\Users\Public\WoA\install.wim\" /Index:1 /ApplyDir:G:\"
2019-02-17 21:55:35.659 +02:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Apply-Image /ImageFile:\"C:\Users\Public\WoA\install.wim\" /Index:1 /ApplyDir:G:\" }
2019-02-17 21:55:35.668 +02:00 [Verbose] Process started sucessfully
2019-02-17 22:38:16.112 +02:00 [Error] An error has ocurred
Installer.Core.Exceptions.DeploymentException: There has been a problem during deployment: DISM exited with code 112.
   at Installer.Core.FullFx.DismImageService.<ApplyImage>d__1.MoveNext() in C:\Users\super\source\repos\Install\Installer.Core.FullFx\DismImageService.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiWindowsDeployer.<ApplyWindowsImage>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiWindowsDeployer.<Deploy>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiDeployer.<DeployWindows>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiDeployer.<DeployCoreAndWindows>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.ViewModels.MainViewModel.<DeployUefiAndWindows>d__59.MoveNext()
2019-02-17 22:38:16.118 +02:00 [Information] Error: There has been a problem during deployment: DISM exited with code 112.

**Comment by patel8786** [comment]
> 
> 
> I get the same error.
> 
> Is it looking for DISM in the wrong place?
> 
> Windows 10 documentation says:
> 
> > DISM comes with Windows 10, in the `c:\windows\system32` folder, but you can run DISM in the command prompt from any location. You have to be running from a Command Prompt as administrator to use use DISM.
> 
> I can see DISM.exe in that folder but it's looking for it in `C:\WINDOWS\SysNative\dism.exe`
> The logging seems to say that DISM was started and returned the error code but I'm doubting that.
> 
> I've copied dism.exe and the dism folder from `system32 `to `C:\WINDOWS\SysNative\` and going to try again.
> 
> > 2019-02-17 21:55:35.658 +02:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "3204780842", Images: [ImageMetadata { DirectoryCount: "19016", FileCount: "85770", TotalBytes: "13896743737", HardLinkBytes: "6092415839", CreationTime: Time { HighPart: "0x01D4C09E", LowPart: "0xE35BD26F" }, LastModificationTime: Time { HighPart: "0x01D4C09F", LowPart: "0xA17D02E1" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Core", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.18836.1000;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-GB", Default: "en-GB" }, Version: Version { Major: "10", Minor: "0", Build: "18836", SpBuild: "1000", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Home", Description: "Windows 10 Home", Flags: null, DiplayName: "Windows 10 Home", DisplayDescription: "Windows 10 Home", Index: "1" }] }
> > 2019-02-17 21:55:35.659 +02:00 [Verbose] We are about to run DISM: "C:\WINDOWS\SysNative\dism.exe" "/Apply-Image /ImageFile:"C:\Users\Public\WoA\install.wim" /Index:1 /ApplyDir:G:"
> > 2019-02-17 21:55:35.659 +02:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Apply-Image /ImageFile:"C:\Users\Public\WoA\install.wim" /Index:1 /ApplyDir:G:" }
> > 2019-02-17 21:55:35.668 +02:00 [Verbose] Process started sucessfully
> > 2019-02-17 22:38:16.112 +02:00 [Error] An error has ocurred
> > Installer.Core.Exceptions.DeploymentException: There has been a problem during deployment: DISM exited with code 112.
> > at Installer.Core.FullFx.DismImageService.d__1.MoveNext() in C:\Users\super\source\repos\Install\Installer.Core.FullFx\DismImageService.cs:line 39
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> > at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > at Installer.Raspberry.Core.RaspberryPiWindowsDeployer.d__9.MoveNext()
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> > at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > at Installer.Raspberry.Core.RaspberryPiWindowsDeployer.d__5.MoveNext()
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> > at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > at Installer.Raspberry.Core.RaspberryPiDeployer.d__7.MoveNext()
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> > at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > at Installer.Raspberry.Core.RaspberryPiDeployer.d__3.MoveNext()
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> > at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > at Installer.Raspberry.ViewModels.MainViewModel.d__59.MoveNext()
> > 2019-02-17 22:38:16.118 +02:00 [Information] Error: There has been a problem during deployment: DISM exited with code 112.

Copying DISM to that location didn't work. Looking at the timestamps DISM started long before the error occurred.

PS: if it helps any for me this error occurrs at 90%

**Comment by milannakum** [comment]
> I downloaded the required files and started the installation, but it seems to work fine until I get up to 64 %, and then it says, Error code 112, there has been a problem during your deployment: DISM exited with code 112

@princessAmy @patel8786 

I got the same thing first time, but run it again and that might solve that issue. I did run 3x to successfully complete the process.

This issue seems because of threading stuck at somewhere waiting for another Task to complete (which actually might be complete but didn't get proper notification of completion).

**Comment by cleveHEX** [comment]
Use https://github.com/WOA-Project/WOA-Deployer-Rpi
